### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by yamamoto-yuta** [yamamoto-yuta/yamamoto-yuta.github.io#11]
```yaml
blog_title: yamamoto-yuta.github.io
site_introduction: Yamamoto's personal blog
copylight_name: YutaYamamoto
copylight_url: https://github.com/yamamoto-yuta
root_url: https://yamamoto-yuta.github.io
issues_page_url: https://github.com/yamamoto-yuta/yamamoto-yuta.github.io/issues
favicon_image_url: https://user-images.githubusercontent.com/42331656/175183205-06dc6033-af20-44b9-ae3d-c3e68770a1f3.png
author_name: Yuta Yamamoto
author_introduction: It's me.
avatar_image_url: https://user-images.githubusercontent.com/42331656/175183205-06dc6033-af20-44b9-ae3d-c3e68770a1f3.png
sns:
  - name: GitHub
    url: 
#  - name: Twitter
#    url: 
#  - name: Facebook
#    url: 
#  - name: LinkedIn
#    url: 
#  - name: Instagram
#    url: 
#  - name: Youtube
#    url: 
```
